### ISSUE TITLE
problem with function import points

### ISSUE THREAD

**Issue by F1uviati1is** [aarkilanian/dci#11]
Hello @aarkilanian ,
i am trying to find my confidence in computing DCI with dci package. So far i havent been able to create simple river net object. I ended up with folowing script and error i didnt manage to solv.

# Script:
`library(dci)

setwd("C:/Users/boris.prudik/Desktop/pracovni_zaloha21_9_2022_11_00/for_R/GIS/dci/botic")
getwd()

reka <- import_rivers(rivers = "Botic.shp")
jezy <- import_points(pts = "Botic_jezy.shp", type= "poi")
usti <- import_points(pts = "Botic_usti.shp", type = "outlet")

ricni_sit <- river_net(rivers = reka, barriers = jezy, outlet = usti, tolerance = 100)
`
# Error:
_> ricni_sit <- river_net(rivers = reka, barriers = jezy, outlet = usti, tolerance = 100)_
**Error in river_net(rivers = reka, barriers = jezy, outlet = usti, tolerance = 100) : 
  Barriers must first be imported with `import_points`**

In attachment i provide used geospatial layers
[botic.zip](https://github.com/aarkilanian/dci/files/10057790/botic.zip)

I woud be greatfull for any response,
Boris Prudík
(boris.prudik@nature.cz)

**Comment by aarkilanian** [comment]
Hi Boris,

The problem is that you've imported `jezy` as points of interest. That's the `type = "poi"` part of your script. It should be specified as barriers by setting the type parameter to `barriers` as such:

`jezy <- import_points(pts = "Botic_jezy.shp", type = "barriers")`

This should allow you to generate a river_net object. However, I noticed your spatial data is not in a projected coordinate system. You must project them to use the dci package since it depends on measuring geographic distances.

I hope this helps!

**Comment by F1uviati1is** [comment]
Hi,
thanks very much for help.
I projected my data in to crs and created sf objects (*description of inputs you can find at the end of this message*). Still had problems to make river_net object.


```{r }
> dta_river    <- import_rivers(rivers = dta_tok, quiet = T)
> dta_barriers <- import_points(pts = dta_prekazky_vsechny, type= "barriers")
> dta_outlet   <- import_points(pts = southernmost_point, type = "outlet")

> ricni_sit    <- river_net(rivers = dta_river, barriers = dta_barriers, outlet = dta_outlet, tolerance = 10)

Error in if (!(is.null(poi)) & !(attr(poi, "sf_column") == rivers_sf_col)) { : 
  argument is of length zero
```
This was first important error i got. I didnt underestand, why there is problem with "poi" if it should be optional argument. Only way i was able to deal with this one was to modyfied function `r rive_net` i was. After modification the function coudnot find function `r split_rivers_at_points` with folowing error:

```{r }
> ricni_sit    <- alt_river_net(rivers = dta_river, barriers = dta_barriers, outlet = dta_outlet, tolerance = 10)
No divergences detected.
No complex confluences found.
 Error in split_rivers_at_points(rivers, user_nodes, tolerance) : 
could not find function "split_rivers_at_points"
```
So i run your sourcecode function within the script. Unfortunately it couldnt solve the issue because i got only other error:

```{r }
> ricni_sit    <- alt_river_net(rivers = dta_river, barriers = dta_barriers, outlet = dta_outlet, tolerance = 10)
No divergences detected.
No complex confluences found.
 Error in sf::st_line_sample(rivers[riv_ind, ], density = 1/1) : 
st_line_sample for longitude/latitude not supported; use st_segmentize?
```
So i let AI to rewrite both functions `r river_net` and `r split_rivers_at_points` to use `r st_segmentize` insted of `r st_line_sample` but just got another error.

**Could you pleas give me a hint, where to look for potentional issues?**

I was trying this with
R version 4.2.2 (2022-10-31 ucrt) and R version 4.2.3 (2023-03-15 ucrt)

[1] ggplot2_3.4.0  rgdal_1.6-2    sf_1.0-9       sp_1.5-1       dci_0.0.0.9000
and
[1] ggplot2_3.4.2  rgdal_1.6-6    sf_1.0-12       sp_1.6-0       dci_0.0.0.9000

Objects:
```{r }
> dta_prekazky_vsechny
Simple feature collection with 9687 features and 0 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 12.10833 ymin: 48.60378 xmax: 18.8372 ymax: 51.01345
Geodetic CRS:  WGS 84
First 10 features:
                    geometry
1  POINT (15.76366 50.68898)


> dta_tok
Simple feature collection with 518 features and 12 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 15.96933 ymin: 48.88946 xmax: 16.67663 ymax: 49.78951
Geodetic CRS:  WGS 84
First 10 features:
     TYPCEVT_K           TYPCEVT_P           FID_ZBG         KODPOVODI USEK_ID   JMENO
607          1 evidovaný vodní tok 11526899515785216 4-15-02-0130-0-00    <NA> Svitava


> southernmost_point
Simple feature collection with 1 feature and 0 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 16.62345 ymin: 48.88946 xmax: 16.62345 ymax: 48.88946
Geodetic CRS:  WGS 84
                   geometry
1 POINT (16.62345 48.88946)
```

Thanks for reading this,
Boris
